### ISSUE TITLE
query_result.rb 

### ISSUE THREAD

**Issue by Tsukehan** [ttanimichi/bigquery-client#10]
bigquery-clientの開発、ありがとうございます。
当方はRailsを入れていない者ですが、
以下のファイルにおいて、to_hがundefined methodでこけました。
/usr/local/share/gems/gems/bigquery-client-0.4.0/lib/bigquery-client/query_result.rb 

そのため、以下のように修正したら動きましたので、ご報告いたします。

旧: [column_names, values].transpose.to_h
新: [column_names, values].transpose.inject({}){|h, x| h[x[0]] = x[1];h}

**Comment by yamotonalds** [comment]
同じ問題が発生した者です。
Ruby 2.1より古いと発生しますね。

こちらはGemfileに

```
gem 'backports', require: 'backports/2.1.0/array/to_h' # for bigquery-client
```

と書いて回避してます。
ご参考までに。

**Comment by ttanimichi** [comment]
(English follows Japanese)

ああ、すいません、`Array#to_h` は Ruby 2.1 で入った機能でした。とりいそぎ Ruby のバージョンを上げてもらうか、@yamotonalds さんの仰っているバックポートを使って頂ければ動くと思います。近々この件の対応を入れた v0.4.1 をリリースします。よろしく願いします。

I forgot `Array#to_h` is a new feature of Ruby 2.1. It doesn't work in older version of Ruby. I'll fix it and release v0.4.1 soon. Thanks.

**Comment by Tsukehan** [comment]
ご指摘のとおり、Ruby2.0系を使っていました。
お二方、どうもありがとうございました。
